### ISSUE TITLE
helm-source-session should not be included in helm-C-x-b-sources if emacs-session is not present

### ISSUE THREAD

**Issue by glyph** [emacs-helm/helm-cmd-t#30]
This causes helm-cmd-t to raise an error out of the box; see https://github.com/emacs-helm/helm/issues/1479#

**Comment by lewang** [comment]
thanks!

**Comment by glyph** [comment]
No problem, thanks for this very useful package :).

**Comment by lewang** [comment]
fixed in https://github.com/emacs-helm/helm-cmd-t/pull/35
