### ISSUE TITLE
helm-cmd-t stopped working on my computer for some reason (???)

### ISSUE THREAD

**Issue by glyph** [emacs-helm/helm-cmd-t#31]
I just updated my emacs packages today and helm-cmd-t showed every git repo as empty.  When I downgraded again (I now always make backups thanks to bugs like this) it started working.

**Comment by glyph** [comment]
Um, I may have misdiagnosed.  I _thought_ it worked after rolling back, but either it only worked for a  second or it was some cache effect. Now it doesn't work with the older helm either.

**Comment by glyph** [comment]
I thought maybe it was because Homebrew had also just upgraded `git`, but, no.  I tried on a different machine with a similar configuration - also broken there.  I am at a loss.

**Comment by glyph** [comment]
To try and debug, I did `(display-buffer (list-buffers-noselect nil (buffer-list)))` and selected the hidden helm source buffer.  It has all the files I expect to see in it, so… where else might I look to see why they're not making it to the UI?

**Comment by lewang** [comment]
can you try https://github.com/emacs-helm/helm-cmd-t/pull/35 ?  I'll re-open if this is a totally different issue.
