### ISSUE TITLE
helm-cmd-t-get-create-source-dir not working

### ISSUE THREAD

**Issue by point-free** [emacs-helm/helm-cmd-t#32]
helm-cmd-t-get-create-source-dir seems to not be working. 

```
(defun helm-cmd-t-ad-hoc-example ()
  "Choose file from test folder."
  (interactive)
    (helm :sources (list (helm-cmd-t-get-create-source-dir "~"))))
```

gives: `assq: Wrong type argument: bufferp, nil`

This is a fresh installation from melpa.

```
helm               20160817.1042 installed
helm-cmd-t         20150823.1157 installed
```

**Comment by gabhab** [comment]
I also have this problem. Rolling helm back to a version from January works OK. Here's a backtrace:

Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
  re-search-forward("^\\(?4:[ 	]*\\)\\(?1::\\(?2:\\S-+\\):\\)\\(?:\\(?3:$\\)\\|[ 	]+\\(?3:.*?\\)\\)\\(?5:[ 	]*\\)$" 158397 t)
  org-element-node-property-parser(158397)
  org-element--current-element(158397 element node-property nil)
  byte-code("\212\214~\210b\210	\205\n\205\306\307!\205\310\311\"\312\f;\203+\313\314
\f#\2021\315\fA@
\"*2\311\2113\3114\204f\3165\317 \21167\3206P8\321 ,\203\\\3224\311y\210\323\311w\210\324 \210\202H2U\203\225\325\3269\203\217\327\f;\203\205\313\314
\f#\202\213\315\fA@
\"*\202\220\"\210\202H\330\3165\317 \21167\3206P+2\316#\203\274\311y\210\323\311w\210\324 \210\3224\202HdU\203\310S\202\311:\331\f;\203\335\313\314
\f#\202\343\315\fA@
\"*\206\3512b\210\332:\f;\203\375\313\314
\f#\202\315\fA@
\"*\211;X\205.;b\205.\327:\f;\203$\313\314
\f#\202*\315\fA@
\"*\211:)\204\353:\203Gm\203A:\202G:`3*\332\f\f;\203Y\313\314
\f#\202_\315\fA@
\"*\206z\212\3165\317 \21167\3206P8\333 \210,`)\f<;9\203\257`U\203\223\325\326<\"\210\202\257=\211=\205\246\334 \206\246\335=\336 \")\203\257\325\337\311\"\210\f\204\376\340;\3044\341<\f;\203\313\313\314
\f#\202\321\315\fA@
\"*$\211\327<>\211;\203\353\342\f\311
>$\202\370\fA\343\fA@
>#\240\210\f+\210\344\f!\210\332\f\f;\203\313\314
\f#\202\315\fA@
\"*\f\211:\204&\f;\205.\345\202.\f@9\205.\f@)?\211@X\203\313d@U\204\313@b\210?\311A?A\203\230\346?\347\"\203\\\350\202\305\346?\351\"\203h\322\202\305\346?\352\"\203t\353\202\305\346?\354\"\203\200\355\202\305\346?\350\"\203\214\322\202\305\346?\356\"\205\305\357\202\305\346?\353\"\203\244\353\202\305\346?\355\"\203\260\355\202\305\346?\322\"\203\274\354\202\305\346?\357\"\205\305\357*4\202\351?B>\204\333\325\326\f\"\210\202\351\331\f\f;\203\354\313\314
\f#\202\362\315\fA@
\"*\360\f\f;\203\313\314
\f#\202\n\315\fA@
\"*CD9\204HD\205\340C\205\340DW\2044DU\205\340?\361>?\205\340CV\204HCU\205\340dU\205\3403\206ODb\210\3113?\316A?A\203\250\346?\347\"\203l\350\202\325\346?\351\"\203x\322\202\325\346?\352\"\203\204\353\202\325\346?\354\"\203\220\355\202\325\346?\350\"\203\234\322\202\325\346?\356\"\205\325\357\202\325\346?\353\"\203\264\353\202\325\346?\355\"\203\300\355\202\325\346?\322\"\203\314\354\202\325\346?\357\"\205\325\357*4\f<C\211;*\204\351\325\326\f\"\210*\311\202" [pos org-element-use-cache org-element--cache cached element property derived-mode-p org-mode org-element--cache-find nil :begin get-text-property 0 plist-get t org-get-limited-outline-regexp "^" outline-previous-heading planning " 
	\n" beginning-of-line throw exit :parent re-search-backward :contents-begin :end outline-next-heading input-pending-p time-less-p current-time interrupt org-element--current-element :structure org-add-props plist-put org-element--cache-put plain-text eql headline section inlinetask plain-list item property-drawer node-property table table-row :contents-end (plain-list table) ...] 9)
  org-element--parse-to(158403 t nil)
  byte-code("\306H\307U\203\f\310\311\215\210\306H\312U\203\262\307H\n\203h	\n\211\250\2037\250\2030\fW\202F\f@X\202F\250\203C\f@W\202F\313\314\215*\204h
A@\211.\307	I\210.\312\312HI\210.\306\312I\210)\315\316\317\"\210)\312H\320H\\/0\203\207/0V\203\207\315\321\322\"\210\202\2611\203\234/1Y\203\234\306\323I\210\202\261\324/\3172#3\3253I\210\306\323I\210))\307H\320H\325H4\307H5>\204\313\326\327\330\331#\2104\312H\307H\322C\317\32267893:;3\204\364\332:!\203\364\315\316\317\"\2109\203\3419\323H\211<=\333=>\"\206i\334==?=;\203\"\335\307?=#\202*\336=A@?\"*@=\211=:\204@=;\205J\337\202J=@9\205J=@)\340>\203V@T\202X@
\203g\341=	>#\202h	*)7\203\2669\307H\203\266	;\211\250\203\223\250\203\214\fW\202\242\f@X\202\242\250\203\237\f@W\202\242\313\314\215*\204\26698B89\307H9\202\335	;\211\250\203\322\250\203\313\fW\202\341\f@X\202\341\250\203\336\f@W\202\341\313\314\215*\204\303	\n\232\203\360\315\316\317\"\2106\204\f2\2112\205\342 \206\3432\344 \")\203\307	I\210\3253I\210\315\321\322\"\210\332:!\204<:\322A:\211=A@BA\203?\345A>\203\300=\211=:\204R=;\205\\\337\202\\=@9\205\\=@)\346=\203\300\336B\347\"\211=:\204x=;\205\202\337\202\202=@9\205\202=@)\350=\204\300\336B\345\"\322(\211C\203\277C@\211(\211D\211@:\\\240\210)\351(\233\211E\211@:\\\240\210)CA\211C\204\226*\352\322\211C\205\372C@A\203\331	A>\205\336\336B	\"\211F\203\357\353B	:F\\#\210)CA\211C\204\311\322.\210\333<G\"\322H\211C\203C@\211H\211AA\262\322I\211C\203C@\211I:\322A:\211=A@BA\203@\345A>\203\301=\211=:\204S=;\205]\337\202]=@9\205]=@)\346=\203\301\336B\347\"\211=:\204y=;\205\203\337\202\203=@9\205\203=@)\350=\204\301\336B\345\"\322(\211C\203\300C@\211(\211D\211@:\\\240\210)\351(\233\211E\211@:\\\240\210)CA\211C\204\227*\352\322\211C\205\373C@A\203\332	A>\205\337\336B	\"\211F\203\360\353B	:F\\#\210)CA\211C\204\312\322.\210CA\211C\204 *CA\211C\204\f*\334<=?=;\203)\335\307?=#\2021\336=A@?\"*@3\203\205\3543=?=;\203P\335\307?=#\202X\336=A@?\"*@X\203\205\3473=?=;\203v\335\307?=#\202~\336=A@?\"*\2113\20493\204\231\332:!\203\231\315\316\322\"\210\202\2623\203\262\347<=?=;\203\265\335\307?=#\202\275\336=A@?\"*\211J?\206\334J=?=;\203\334\335\307?=#\202\344\336=A@?\"*\3343=?=;\203\374\335\307?=#\202\336=A@?\"*W)\203\262<\3473F?\211=;\203&\355=\322?F$\2027=A\353=A@?F#\240\210=+\210\3453=?=;\203P\335\307?=#\202X\336=A@?\"*\211K\203\261\345<=?=;\203v\335\307?=#\202~\336=A@?\"*\203\261<\345KF?\211=;\203\236\355=\322?F$\202\257=A\353=A@?F#\240\210=+\210)0\203\302@0V\203\302\3176)9\312H\2117\203\3249\312H\202\3338\211A8\2429*\202\364.\317\207" [request key next b a org-element--cache-sync-requests 5 0 end-phase (byte-code "\211\205\306 \206\307\310 \")\203\311\312\313\"\210	\314H	\315H\n\314H>\204-\316\317\320\321#\210\n\322H\314H\313\211\211$%&'%\203U%\315H\211((\323()\"\206\270\324((*(;\203m\325\314*(#\202u\326(A@*\"*+(\211(:\204\213(;\205\225\327\202\225(@9\205\225(@)\330>\203\241+T\202\243+,-\203\265\331(,)#\202\267,*)\211,'.\211/\250\203\336.\250\203\325/.W\202\360/.@X\202\360.\250\203\355/@.W\202\360\332\333\215*\203\375%\322H%\202Q',.\211/\250\203!.\250\203/.W\2023/.@X\2023.\250\2030/@.W\2023\332\333\215*\203G($,%\314H%\202Q($,\313%*\202?$\203\\\324$(*(;\203q\325\314*(#\202y\326(A@*\"*01\203\272
1.\211/\250\203\244.\250\203\233/.W\202\266/.@X\202\266.\250\203\263/@.W\202\266\332\333\215*\203\3020&X\202\376\f\203C$\2112\203\3732\f=\204\373\3342(*(;\203\354\325\314*(#\202\364\326(A@*\"*\2112\204\3162)\203C\f\204.\335$(*(;\203\325\314*(#\202$\326(A@*\"*&V\203.$$(\336\n(\"\210\337(3\")\210\202X	\314
I\210	\3220I\210	\340\322I\210\311\341\313\"\210)\202a\311\342\343\"\210.\202" [time-limit request org-element--cache cl-struct-avl-tree--tags last-container data-key input-pending-p time-less-p current-time throw interrupt nil 0 2 error "%s accessing a non-%s" avl-tree--dummyroot avl-tree- 1 gethash :begin get-text-property plist-get plain-text (item table-row) puthash exit (byte-code "\203/	\203/\302	\"\203\303\304\305\"\210\202\302	\"\203&\303\304\306\"\210\202A	A\202?\2055	\207" [a b car-less-than-car throw exit t nil] 3) :parent :end avl-tree-delete remhash 5 end-phase quit t data node end beg element org-element--cache-sync-keys property begin key org-element--cache-sync-requests b a pos next ...] 7) 1 exit (byte-code "\203/	\203/\302	\"\203\303\304\305\"\210\202\302	\"\203&\303\304\306\"\210\202A	A\202?\2055	\207" [a b car-less-than-car throw exit t nil] 3) throw quit t 3 interrupt nil 2 org-element--parse-to 4 error "%s accessing a non-%s" avl-tree--dummyroot avl-tree- zerop gethash :begin get-text-property plist-get plain-text (item table-row) puthash input-pending-p time-less-p current-time :structure plain-list :parent item 6 (:begin :contents-begin :contents-end :end :post-affiliated) plist-put :end org-add-props next-request limit threshold future-change ...] 8)
  org-element--cache-process-request([158338 158311 152290 92 (property-drawer (:begin 158029 :end 158105 :contents-begin 158045 :contents-end 158096 :post-blank 0 :post-affiliated 158029 :parent nil)) 1] 158369 291462 nil nil)
  byte-code("\203D@A@\306	\n\205\n\307H\211?\205\310\311 \f\"
%\210\n\203=\n\211\f\312\f\312H	\312H\\I\210)\n\313	\313HI\210A\211\204\306\207" [org-element--cache-sync-requests request next threshold org-element-cache-sync-duration future-change org-element--cache-process-request 0 time-add current-time 3 2 v] 8)
  org-element--cache-sync(#<buffer todo.org> 291462)
  org-element-at-point()
  byte-code("db\210\302\303e\304#\203\"\305 \306!\307=\203\310\311\312\313\"\"\210)\202	\207" [element default-category re-search-backward "^[ 	]*#\\+CATEGORY:" t org-element-at-point org-element-type keyword throw buffer-category org-element-property :value] 5)
  org-refresh-category-properties()
  byte-code("\306!\203\fq\210\202\307!\210\310!q\210~\210\311\312!\210`\313\n>\204&\314 \210\315\n>\204/\316 \210\317\n>\2048\320 \210\321\n>\204C\322\323\324\"\210\325\f\"\325
)\"\325*+\"*\325,-.#/\326/!0\3270!*,1\203\2752\3303\2114\203\2744@3\3313@5\"\2116\203\2536\3256A3A\"/\326/!0\3270!*\241\210\202\26235B5)4A\2114\204}*\332 7\333\21189\333:\330\211;<\330=\334\216\212\335ed>#\210?\203eb\210\336@\330\333#\203\337\333!\203\345\340\341 \342\333!A#\210\202\345eb\210\343\344B\"C\336C\330\333#\203.\345 D\346\216\347\333!*\203\340\350\224\342\333!E#\210\202.		b\207" [file pos org-agenda-ignore-properties org-todo-keywords-for-agenda org-todo-keywords-1 org-done-keywords-for-agenda bufferp org-check-agenda-file org-get-agenda-file-buffer org-set-regexps-and-options tags-only category org-refresh-category-properties stats org-refresh-stats-properties effort org-refresh-effort-properties appt org-refresh-properties "APPT_WARNTIME" org-appt-warntime append copy-sequence delete-dups nil assoc buffer-modified-p t ((byte-code "\204\301\302!\210\302\207" [modified restore-buffer-modified-p nil] 2)) remove-text-properties re-search-forward org-at-heading-p add-text-properties point-at-bol org-end-of-subtree format "^\\*+ .*\\<%s\\>" match-data ((byte-code "\301\302\"\207" [save-match-data-internal set-match-data evaporate] 3)) org-in-commented-heading-p 0 org-done-keywords org-todo-keyword-alist-for-agenda org-todo-key-alist org-tag-alist-for-agenda org-tag-alist org-tag-persistent-alist list res org-group-tags ...] 5)
  org-agenda-prepare-buffers(("~/Dropbox/orgmode/todo.org"))
  org-agenda-prepare("Day/Week")
  byte-code("\206)	\203(\n\203;\203\306\307\n#\202%\n\203$\306\310\n\"\202%\311\206)\f\312\313!\210
\2064@\211;\203B\314\315\316\317
#!\320\321!\210\322\321!\210\323A\206WB\206WC!A\324 D
\206dDE\325AE\"\211F\326=\204{F\327=\205}GG\330\316\331\"\211HIG\203\224F\326W\203\231E\202\277\332\333E!!JGKJKZLEL\334W\203\271\326\202\272\334L\\Z+\211MCN\334OP?QRS\316\211TU\316\211VW\316\211XY\316\211LZ\316\211[\\\316\211]^\316_\335\336`D
\336ADa\257bFS\334cdcdW\203*N@TNBNcT\211c\202*N\237\211N@]Ne\337e!@)\206B\334T^\340N@fg\341g!fL*\210\342`fg\341g!fL*\210\343\323A!fg\341g!fL*\210h\204\362N@iNe\337e!@)j\344i!k\344j!l`Tm\203\262\345\346m!\316\347\350$\351\261\210\202\340\352A!\353jiZ\354W\203\333klU\203\321\306\355k\"\202\334\306\356kl#\202\334\357\360\261\210,\361T`S\347\350\362\317F#\210\363T!\210N\211AN\242\211L\203\374\333L!Y`TLDU\211\\\204 Z\204&LEU\203&`Z\2023Z\2033[\2043`[HI\316WI\211AI\242\211X\203N\364\365\215\210\202:n\203i\317o\366\367!\210\370Y!V\371WV\"W)W\204sp\203\362OTOq;\203\211\372q\373Y!\"\202\216qY!\351\261\210\374T`S\347\375Y!$\210\374T`S\362\317$\210\374T`S\376\317$\210\374T`S\377O$\210\\\203\310\374T`S\324\317$\210\201yWF\\#\211W\203\343\201zW\321\"\351\261\210\374T`S\201{L$\210\374T`S\377O$\210\202\362r\203U]\203U\330\316\331\"\346s!\316tu\201|u\201}\"u\201~u\201]#u\201~u\201\200^#u\201~u\201\201\321#u\201\202\201\203u\"\211tc\210+eb\210v\204b\201\204 \210\201\205e!\203r\201\205d!\204\237dSb\210\201\206\201\207!\210\201\205Z\206\211\201\210!\204\237Z\206\225\201\210b\210\201\206\201\210!\210Z\206\247\201\210b\210\361ed\201\211\321\201\212`
AE\201\213b\201\214w\257#\210S\201\215=\203\325\201\216 \210\201\217 \210\317x\201\220\357!.\207" [org-agenda-buffer-tmp-name org-agenda-sticky org-keys org-match org-agenda-buffer-name start-day format "*Org Agenda(%s:%s)*" "*Org Agenda(%s)*" "*Org Agenda(a)*" org-agenda-prepare "Day/Week" time-to-days org-read-date nil t org-compile-prefix-format agenda org-set-sorting-strategy org-agenda-ndays-to-span org-today org-agenda-span-to-ndays 7 14 org-agenda-files ifmode calendar-day-of-week calendar-gregorian-from-absolute 0 org-agenda-list quote last org-starting-day make-local-variable org-arg-loc org-agenda-current-span org-days-to-iso-week org-add-props copy-sequence face org-agenda-structure "\n" org-agenda-span-name "-agenda" 350 " (W%02d)" " (W%02d-W%02d)" "" ":\n" add-text-properties ...] 12)
  org-agenda-list(nil)
  call-interactively(org-agenda-list)
  byte-code("\306	\307 	\232\203\310\202\n\311\306\312\313\"\"\314
\"p@\315\316 !A\306\211BC\306\211DE\306\211FGH\204`\317\320!\203K\204Q\321\322\323\306#\210\306IJ\306\211\223\210K\306\211\223\210\321\324\325\306#\210\321\324\326\306#\210pLM\204\202\327!\211G@MGANO\203\215\330\331M\"H\204\330N\203\330\321\322\323AC#\210N\332=\203\272pIJ\333 \306\223\210K\334 \306\223\210\202\330N\335=\203\330\212pI\336\337!\210J`\306\223\210K\340\337!\306\223\210)\341M\"\211B\203\342B89\204\364\343\342B8!\203\342B8D\344\345B8!E\346B8FO\203#E;\203\330\347ME#\206\"\330\331M\"\321\324\325F#\210D\350=\2039\351F\352\"\202\237D\353=\203H\351F\354\"\202\237D\355=\203W\351F\356\"\202\237D\357=\203f\351F\360\"\202\237D\361=\203u\351F\362\"\202\237D\363=\203\204\351F\364\"\202\237D\365=\203\223\351F\366\"\202\237D\367=\203\242\351F\370\"\202\237D\371=\203\264\372 \210\351F\373\"\202\237D\374=\203\306\372 \210\351F\375\"\202\237D\376=\203\330\372 \210\351F\377\"\202\237\343D!\203\351\351F\201S\"\202\237\201TD!\203\374\351F\201U\"\202\237\201V\201WD\"\202\237\201XBA@B\211AA\262\"\202\237M\201Y\232\203-\f\201Z\303!\202\237M\201[\232\203@\201\\\201]!\202\237M\201^\232\203S\201\\\201_!\202\237M\201`\232\203y\201_P\206g\201aPQPR\201\\Q!+\202\237M\201b\232\203\214\201\\\201c!\202\237M\201d\232\203\262\201cP\206\240\201ePQPR\201\\Q!+\202\237M\201f\232\203\305\201\\\201g!\202\237M\201h\232\203\353\201gP\206\331\201iPQPR\201\\Q!+\202\237M\201j\232\203\376\201\\\201k!\202\237M\201l\232\203\201g\306\201m\"\210\201n\201o\201p\337\211$\202\237M\201q\232\203_\201r\201s!\204:\201V\201t!\210N?\205\237\321\322\323AC#\210\201uPPQPR\201\\Q!+\202\237M\201v\232\203r\201\\\201w!\202\237M\201x\232\203\205\201\\\201y!\202\237M\201z\232\203\230\201Z\201{!\202\237\201V\201|!.\207" [prefix-descriptions org-agenda-buffer-name org-agenda-window-setup org-agenda-custom-commands org-agenda-custom-commands-orig org-agenda-custom-commands-contexts nil buffer-name current-window delq mapcar #[(x) "A;\203\f	B\302\207A@;\203\207A@\204'@\303\211AA\262BB\207@\303ABB\207" [x prefix-descriptions nil ""] 4] org-contextualize-keys buffer-file-name buffer-base-buffer boundp org-agenda-keep-restricted-file-list put org-agenda-files org-restrict org-agenda-redo-command org-lprops last-args org-agenda-get-restriction-and-command format "*Org Agenda(%s)*" region region-beginning region-end subtree org-back-to-heading t org-end-of-subtree assoc 2 functionp eval 3 4 "*Org Agenda(%s:%s)*" agenda org-let (org-agenda-list current-prefix-arg) agenda* (org-agenda-list current-prefix-arg nil nil t) alltodo (org-todo-list current-prefix-arg) search (org-search-view current-prefix-arg org-match nil) stuck ...] 6)
  #[(&optional arg org-keys restriction) "\300\301\215\207" [exit (byte-code "\306	\307 	\232\203\310\202\n\311\306\312\313\"\"\314
\"p@\315\316 !A\306\211BC\306\211DE\306\211FGH\204`\317\320!\203K\204Q\321\322\323\306#\210\306IJ\306\211\223\210K\306\211\223\210\321\324\325\306#\210\321\324\326\306#\210pLM\204\202\327!\211G@MGANO\203\215\330\331M\"H\204\330N\203\330\321\322\323AC#\210N\332=\203\272pIJ\333 \306\223\210K\334 \306\223\210\202\330N\335=\203\330\212pI\336\337!\210J`\306\223\210K\340\337!\306\223\210)\341M\"\211B\203\342B89\204\364\343\342B8!\203\342B8D\344\345B8!E\346B8FO\203#E;\203\330\347ME#\206\"\330\331M\"\321\324\325F#\210D\350=\2039\351F\352\"\202\237D\353=\203H\351F\354\"\202\237D\355=\203W\351F\356\"\202\237D\357=\203f\351F\360\"\202\237D\361=\203u\351F\362\"\202\237D\363=\203\204\351F\364\"\202\237D\365=\203\223\351F\366\"\202\237D\367=\203\242\351F\370\"\202\237D\371=\203\264\372 \210\351F\373\"\202\237D\374=\203\306\372 \210\351F\375\"\202\237D\376=\203\330\372 \210\351F\377\"\202\237\343D!\203\351\351F\201S\"\202\237\201TD!\203\374\351F\201U\"\202\237\201V\201WD\"\202\237\201XBA@B\211AA\262\"\202\237M\201Y\232\203-\f\201Z\303!\202\237M\201[\232\203@\201\\\201]!\202\237M\201^\232\203S\201\\\201_!\202\237M\201`\232\203y\201_P\206g\201aPQPR\201\\Q!+\202\237M\201b\232\203\214\201\\\201c!\202\237M\201d\232\203\262\201cP\206\240\201ePQPR\201\\Q!+\202\237M\201f\232\203\305\201\\\201g!\202\237M\201h\232\203\353\201gP\206\331\201iPQPR\201\\Q!+\202\237M\201j\232\203\376\201\\\201k!\202\237M\201l\232\203\201g\306\201m\"\210\201n\201o\201p\337\211$\202\237M\201q\232\203_\201r\201s!\204:\201V\201t!\210N?\205\237\321\322\323AC#\210\201uPPQPR\201\\Q!+\202\237M\201v\232\203r\201\\\201w!\202\237M\201x\232\203\205\201\\\201y!\202\237M\201z\232\203\230\201Z\201{!\202\237\201V\201|!.\207" [prefix-descriptions org-agenda-buffer-name org-agenda-window-setup org-agenda-custom-commands org-agenda-custom-commands-orig org-agenda-custom-commands-contexts nil buffer-name current-window delq mapcar #[(x) "A;\203\f	B\302\207A@;\203\207A@\204'@\303\211AA\262BB\207@\303ABB\207" [x prefix-descriptions nil ""] 4] org-contextualize-keys buffer-file-name buffer-base-buffer boundp org-agenda-keep-restricted-file-list put org-agenda-files org-restrict org-agenda-redo-command org-lprops last-args org-agenda-get-restriction-and-command format "*Org Agenda(%s)*" region region-beginning region-end subtree org-back-to-heading t org-end-of-subtree assoc 2 functionp eval 3 4 "*Org Agenda(%s:%s)*" agenda org-let (org-agenda-list current-prefix-arg) agenda* (org-agenda-list current-prefix-arg nil nil t) alltodo (org-todo-list current-prefix-arg) search (org-search-view current-prefix-arg org-match nil) stuck ...] 6)] 2 ("/Users/tsg20/.emacs.d/elpa/org-20160509/org-agenda.elc" . 103110) "P"](nil)
  apply(#[(&optional arg org-keys restriction) "\300\301\215\207" [exit (byte-code "\306	\307 	\232\203\310\202\n\311\306\312\313\"\"\314
\"p@\315\316 !A\306\211BC\306\211DE\306\211FGH\204`\317\320!\203K\204Q\321\322\323\306#\210\306IJ\306\211\223\210K\306\211\223\210\321\324\325\306#\210\321\324\326\306#\210pLM\204\202\327!\211G@MGANO\203\215\330\331M\"H\204\330N\203\330\321\322\323AC#\210N\332=\203\272pIJ\333 \306\223\210K\334 \306\223\210\202\330N\335=\203\330\212pI\336\337!\210J`\306\223\210K\340\337!\306\223\210)\341M\"\211B\203\342B89\204\364\343\342B8!\203\342B8D\344\345B8!E\346B8FO\203#E;\203\330\347ME#\206\"\330\331M\"\321\324\325F#\210D\350=\2039\351F\352\"\202\237D\353=\203H\351F\354\"\202\237D\355=\203W\351F\356\"\202\237D\357=\203f\351F\360\"\202\237D\361=\203u\351F\362\"\202\237D\363=\203\204\351F\364\"\202\237D\365=\203\223\351F\366\"\202\237D\367=\203\242\351F\370\"\202\237D\371=\203\264\372 \210\351F\373\"\202\237D\374=\203\306\372 \210\351F\375\"\202\237D\376=\203\330\372 \210\351F\377\"\202\237\343D!\203\351\351F\201S\"\202\237\201TD!\203\374\351F\201U\"\202\237\201V\201WD\"\202\237\201XBA@B\211AA\262\"\202\237M\201Y\232\203-\f\201Z\303!\202\237M\201[\232\203@\201\\\201]!\202\237M\201^\232\203S\201\\\201_!\202\237M\201`\232\203y\201_P\206g\201aPQPR\201\\Q!+\202\237M\201b\232\203\214\201\\\201c!\202\237M\201d\232\203\262\201cP\206\240\201ePQPR\201\\Q!+\202\237M\201f\232\203\305\201\\\201g!\202\237M\201h\232\203\353\201gP\206\331\201iPQPR\201\\Q!+\202\237M\201j\232\203\376\201\\\201k!\202\237M\201l\232\203\201g\306\201m\"\210\201n\201o\201p\337\211$\202\237M\201q\232\203_\201r\201s!\204:\201V\201t!\210N?\205\237\321\322\323AC#\210\201uPPQPR\201\\Q!+\202\237M\201v\232\203r\201\\\201w!\202\237M\201x\232\203\205\201\\\201y!\202\237M\201z\232\203\230\201Z\201{!\202\237\201V\201|!.\207" [prefix-descriptions org-agenda-buffer-name org-agenda-window-setup org-agenda-custom-commands org-agenda-custom-commands-orig org-agenda-custom-commands-contexts nil buffer-name current-window delq mapcar #[(x) "A;\203\f	B\302\207A@;\203\207A@\204'@\303\211AA\262BB\207@\303ABB\207" [x prefix-descriptions nil ""] 4] org-contextualize-keys buffer-file-name buffer-base-buffer boundp org-agenda-keep-restricted-file-list put org-agenda-files org-restrict org-agenda-redo-command org-lprops last-args org-agenda-get-restriction-and-command format "*Org Agenda(%s)*" region region-beginning region-end subtree org-back-to-heading t org-end-of-subtree assoc 2 functionp eval 3 4 "*Org Agenda(%s:%s)*" agenda org-let (org-agenda-list current-prefix-arg) agenda* (org-agenda-list current-prefix-arg nil nil t) alltodo (org-todo-list current-prefix-arg) search (org-search-view current-prefix-arg org-match nil) stuck ...] 6)] 2 ("/Users/tsg20/.emacs.d/elpa/org-20160509/org-agenda.elc" . 103110) "P"] nil)
* org-agenda(nil)
  call-interactively(org-agenda nil nil)
  command-execute(org-agenda)

**Comment by lins05** [comment]
I got the same problem. See helm-cmd-t doesn't work well with Helm 2.0, so I reverted back to an older version of Helm.

**Comment by lewang** [comment]
fixed https://github.com/emacs-helm/helm-cmd-t/pull/35
